### ISSUE TITLE
POLONIEX API to obtain crypto-currency price now requires a captcha

### ISSUE THREAD

**Issue by mohitesh07** [triestpa/Cryptocurrency-Analysis-Python#3]
**POLONIEX API to obtain crypto-currency price now requires a captcha**
def get_json_data(json_url, cache_path)
THE PATH TO THE POLONIEX API NOW REQUIRES A CAPTCHA
https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ETH&start=1420050600.0&end=1515147923.496171&period=86400
SO I AM UNABLE TO PLOT THE PRICES OF DIFFERENT EXCHANGES

**Comment by triestpa** [comment]
Hi @mohitesh07 - I'm guessing that you're receiving an HTTP 403 "Forbidden" error when making the request from python?  This is a common issue (see #2) - Poloniex has pretty aggressive DDoS protection in place, so many networks are essentially blocked from programmatic access.  To get around this problem, I recommend trying on a different WiFi network or using a VPN.

**Comment by mohitesh07** [comment]
@triestpa **ALL THE NETWORKS ARE BLOCKED FROM PROGRAMMATIC ACCESS by POLONIEX API** 
Now it has a google captcha protection, this code was fairly well 4 months ago, but not now!
I am listing the json url your code is trying to fetch,  
https://poloniex.com/public?command=returnChartData&currencyPair=BTC_ETH&start=1420050600.0&end=1515147923.496171&period=86400
it is not giving access to any machines now!

**Comment by triestpa** [comment]
Hi @mohitesh07, the API (including the link that you've provided) works fine for me.  I believe that they are blocking API traffic from your local network, resulting in a failed 401 response in the code and a captcha test in the browser.  Please see my original answer for advice on circumventing this problem.

**Comment by ravivariar** [comment]
@triestpa  Hello Patrick,  I also have the same issue 403 Forbidden,  I will try to explore other option.
Is it possible to get 3 years altcoin data so that I can run more analysis (including dispersion) wrt to BTC.   I will contribute that back to your site,
regards
Ravi.

**Comment by ravivariar** [comment]
@mohitesh07 @triestpa   I have basically downloaded the files manually and will proceed with the data for now thanks Ravi

**Comment by mohitesh07** [comment]
@ravivariar Its working on downloaded data. I'm accepting it as a solution for now.
Regards
