### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/BCHARTS-KRAKENUSD.pkl'

### ISSUE THREAD

**Issue by JafferWilson** [triestpa/Cryptocurrency-Analysis-Python#4]
Kindly, help me, I could not find the way out. Here is the full trace image of the error:  
![screenshot from 2018-01-22 14-07-46](https://user-images.githubusercontent.com/13446197/35211719-aafe4546-ff7d-11e7-8631-fa95e06f5323.png)

Please let me know the reason for this file not found and how to find or generate the file?

**Comment by triestpa** [comment]
Hi @JafferWilson, Have you created a local `data` directory yet for the dataset?

**Comment by JafferWilson** [comment]
@triestpa Yes, I have created it. But got many errors while running your code. I have got th error as I have mentioned and many other similar errors. Please let me know where to get all the pickle files. If you have then kindly share.

**Comment by triestpa** [comment]
@JafferWilson the `get_quandl_data` function downloads the data from Quandl, and saves it as a pickle file.  The error above is about not finding a file - are you also getting an error during the step where it downloads the data?

**Comment by JafferWilson** [comment]
@triestpa oh.. yes. That worked..... thank you.

**Comment by Elton-Lin** [comment]
@triestpa Could you let me know that In what path should I create the "data" directory? Namely, where exactly would "pickle" store the downloaded file. Sorry I am really new to this. Thank you!

@JafferWilson I have the exact same problem as you, so could you kindly let me know how did you resolve it? Thank you!

**Comment by JafferWilson** [comment]
@Elton-Lin 
Try to use the proper API of Quandl with Python. Read the documentation from here:  
[INSTALLATION & AUTHENTICATION](https://docs.quandl.com/docs/python-installation)  
[Get Financial Data Directly into Python](https://www.quandl.com/tools/python)
This will surely resolve your issue. And you have to make changes in the code for importing or downloading the data.

**Comment by Elton-Lin** [comment]
@JafferWilson 
Got it! Apparently I just needed the API key Thank you very much.

**Comment by zaraag1** [comment]
@JafferWilson I'm getting the same error as yours, could you help me with the changes you made with the code to download data/BCHARTS-KRAKENUSD.pkl

**Comment by lpstake** [comment]
@JafferWilson @triestpa What changes are necessary to the code to resolve this?
